# Generated by Django 5.0.6 on 2026-10-08 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaptaskprogress',
            name='completed',
            field=models.BooleanField(default=False, help_text='True if marked complete; False if pending'),
        ),
        migrations.AlterField(
            model_name='roadmaptaskprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when task was marked complete', null=True),
        ),
        migrations.AlterField(
            model_name='roadmaptaskprogress',
            name='skill',
            field=models.CharField(help_text="Skill discipline name (e.g. 'Web Development', 'Graphic Design')", max_length=80),
        ),
        migrations.AlterField(
            model_name='roadmaptaskprogress',
            name='task_index',
            field=models.PositiveSmallIntegerField(help_text='Zero-based index of the task across the 5 stages of this roadmap'),
        ),
        migrations.AlterField(
            model_name='roadmaptaskprogress',
            name='user',
            field=models.ForeignKey(help_text='The learner who completed or toggled this task.', on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
