"""
=============================================================================
Portfolio & Projects API Views (Django REST Framework)
=============================================================================
Provides endpoints for:
 1. GET /api/portfolio/ — List user's portfolio case studies
 2. POST /api/portfolio/ — Create a new portfolio case study
 3. GET /api/portfolio/<id>/ — Retrieve single portfolio case study
 4. PUT /api/portfolio/<id>/ — Update portfolio case study
 5. DELETE /api/portfolio/<id>/ — Delete portfolio case study
 6. GET /api/portfolio/projects/ — List saved practice project plans
 7. POST /api/portfolio/projects/ — Save a practice project brief
 8. DELETE /api/portfolio/projects/<id>/ — Delete a saved project plan
"""

from rest_framework import generics, permissions
from .models import PortfolioEntry, ProjectPlan
from .serializers import PortfolioEntrySerializer, ProjectPlanSerializer


class PortfolioListCreateView(generics.ListCreateAPIView):
    """
    Handles listing and creating portfolio case studies for the authenticated user.
    Automatically binds created records to request.user.
    """
    serializer_class = PortfolioEntrySerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        """Enforces multi-tenant data isolation: users only see their own case studies."""
        return PortfolioEntry.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        """Inject authenticated user into the created model instance."""
        serializer.save(user=self.request.user)


class PortfolioDetailView(generics.RetrieveUpdateDestroyAPIView):
    """
    Handles retrieving, updating (PUT/PATCH), and deleting a specific portfolio entry.
    """
    serializer_class = PortfolioEntrySerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return PortfolioEntry.objects.filter(user=self.request.user)


class ProjectPlanListCreateView(generics.ListCreateAPIView):
    """
    Handles listing and saving practice project briefs generated by ProjectBuilder.
    """
    serializer_class = ProjectPlanSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return ProjectPlan.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ProjectPlanDetailView(generics.DestroyAPIView):
    """
    Handles deleting a saved practice project plan.
    """
    serializer_class = ProjectPlanSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return ProjectPlan.objects.filter(user=self.request.user)
