# Generated by Django 5.0.6 on 2026-10-08 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='description',
            field=models.TextField(help_text='Problem statement and technical solution'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='outcome',
            field=models.TextField(help_text='Measurable business or learning result (e.g. 40% speedup)'),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='project_url',
            field=models.URLField(blank=True, help_text='Live URL or GitHub repository', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='skills_used',
            field=models.CharField(help_text='Comma-separated skill tags (e.g. React, Django)', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='title',
            field=models.CharField(help_text='Case study title', max_length=120),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='tools_used',
            field=models.CharField(help_text='Software or tools used (e.g. Figma, VS Code, Git)', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='user',
            field=models.ForeignKey(help_text='The creator and owner of this portfolio entry.', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='project_type',
            field=models.CharField(help_text='Project archetype (e.g. Landing Page)', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='skill',
            field=models.CharField(help_text='Skill category (e.g. Web Development)', max_length=80),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='title',
            field=models.CharField(help_text='Generated project title', max_length=120),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='user',
            field=models.ForeignKey(help_text='User who saved this practice project brief.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
