# Generated by Django 5.0.6 on 2026-10-08 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchecklistitem',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the user marked this day complete'),
        ),
        migrations.AlterField(
            model_name='planchecklistitem',
            name='day_number',
            field=models.PositiveSmallIntegerField(help_text='Day index (1 to 7)'),
        ),
        migrations.AlterField(
            model_name='planchecklistitem',
            name='plan',
            field=models.ForeignKey(help_text='The parent UserPlan this checklist task belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='plans.userplan'),
        ),
        migrations.AlterField(
            model_name='planchecklistitem',
            name='task',
            field=models.TextField(help_text='Actionable starter instructions for this day'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this personalized roadmap plan.', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
